---
- hosts: speedtest-atlanta
  gather_facts: yes

  tasks:
    - name: Dump Date and Service Status
      shell: date >> testing.out ; ps -ef |grep OoklaServer >> /tmp/testing.out

    - name: Change to the OoklaServer working directory and stop service.
      shell: ./ooklaserver.sh stop >> /tmp/testing.out
      args:
        chdir: /opt/ookla/Netgauge-Server-2.6/Linux-x86_64/

    - name: Echo Shutdown to Log.
      shell: echo "Service Terminated" >> /tmp/testing.out

    - name: Change to the OoklaServer working directory and start service.
      shell: ./ooklaserver.sh start >> /tmp/testing.out
      args:
        chdir: /opt/ookla/Netgauge-Server-2.6/Linux-x86_64/

    - name: Echo Start to Log.
      shell: echo "Service Started" >> /tmp/testing.out
