- hosts: dukespapp01
 
  tasks:
    - name: Dump Date and Service Status
      shell: date ; ps -ef |grep OoklaServer >> /tmp/asr.log

    - name: Change to the OoklaServer working directory and stop service.
      shell: ./ooklaserver.sh stop 
      args:
        chdir: /opt/ookla/server

    - name: Echo Shutdown to Log.
      shell: echo "Ookla Service Terminated" >> /tmp/asr.log

    - name: Change to the OoklaServer working directory and start service.
      shell: ./ooklaserver.sh start 
      args:
        chdir: /opt/ookla/server

    - name: Echo Start to Log.
      shell: echo "Ookla Service Started" >> /tmp/asr.log
