- hosts: dukespapp01
 
  tasks:
    - name: Dump Date and Service Status
      shell: date >> /tmp/asr.log
      
    - name: Change to the OoklaServer working directory and restart service.
      shell: ./ooklaserver.sh restart 
      args:
        chdir: /opt/ookla/server

    - name: Echo Re-Start to Log.
      shell: echo "Ookla Service Re-Started" >> /tmp/asr.log
